### *INSTALLING the libraries for the CHEMBL database using the python command*

In [ ]:
! pip install chembl_webresource_client

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.8-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 KB 2.3 MB/s eta 0:00:00
Requirement already satisfied: urllib3 in /usr/local/lib/python3.8/dist-packages (from chembl_webresource_client) (1.24.3)
Collecting requests-cache~=0.7.0
  Downloading requests_cache-0.7.5-py3-none-any.whl (39 kB)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.8/dist-packages (from chembl_webresource_client) (2.25.1)
Requirement already satisfied: easydict in /usr/local/lib/python3.8/dist-packages (from chembl_webresource_client) (1.10)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2022.12.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.18.4->chembl_webresource_client) (4.0.0)
Collecting attrs<22.0,>=21.2
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 KB 4.9 MB/s eta 0:00:00
Collecting url-normalize<2.0,>=1.4
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Collecting itsdangerous>=2.0.1
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Requirement already satisfied: pyyaml>=5.4 in /usr/local/lib/python3.8/dist-packages (from requests-cache~=0.7.0->chembl_webresource_client) (6.0)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from url-normalize<2.0,>=1.4->requests-cache~=0.7.0->chembl_webresource_client) (1.15.0)
Installing collected packages: url-normalize, itsdangerous, attrs, requests-cache, chembl_webresource_client
  Attempting uninstall: itsdangerous
    Found existing installation: itsdangerous 1.1.0
    Uninstalling itsdangerous-1.1.0:
      Successfully uninstalled itsdangerous-1.1.0
  Attempting uninstall: attrs
    Found existing installation: attrs 22.2.0
    Uninstalling attrs-22.2.0:
      Successfully uninstalled attrs-22.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 1.1.4 requires itsdangerous<2.0,>=0.24, but you have itsdangerous 2.1.2 which is incompatible.
Successfully installed attrs-21.4.0 chembl_webresource_client-0.10.8 itsdangerous-2.1.2 requests-cache-0.7.5 url-normalize-1.4.3

## *importing libraries*

In [ ]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

## *search for the TARGETING PROTEIN*

Target search for the ***hypertension*** ***Angiotensin II***

In [ ]:
target = new_client.target
target_query = target.search('Angiotensin II')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Rattus norvegicus,Angiotensin II receptor,25.0,False,CHEMBL2094112,"[{'accession': 'P29089', 'component_descriptio...",PROTEIN FAMILY,10116
1,[],Sus scrofa,Angiotensin type II receptor,24.0,False,CHEMBL1163122,"[{'accession': 'Q2XUH7', 'component_descriptio...",SINGLE PROTEIN,9823
2,[],Rattus norvegicus,Angiotensin II receptor (AT-1) type-1,24.0,False,CHEMBL2094250,"[{'accession': 'P29089', 'component_descriptio...",PROTEIN FAMILY,10116
3,[],Homo sapiens,Angiotensinogen,24.0,False,CHEMBL3596085,"[{'accession': 'P01019', 'component_descriptio...",SINGLE PROTEIN,9606
4,"[{'xref_id': 'P35351', 'xref_name': None, 'xre...",Rattus norvegicus,Angiotensin II type 2 (AT-2) receptor,23.0,False,CHEMBL257,"[{'accession': 'P35351', 'component_descriptio...",SINGLE PROTEIN,10116
...,...,...,...,...,...,...,...,...,...
420,[],Rattus norvegicus,Voltage-gated sodium channel,1.0,False,CHEMBL3988641,"[{'accession': 'O88457', 'component_descriptio...",PROTEIN FAMILY,10116
421,[],Homo sapiens,Voltage-gated calcium channel,0.0,False,CHEMBL2363032,"[{'accession': 'O95180', 'component_descriptio...",PROTEIN COMPLEX GROUP,9606
422,[],Homo sapiens,26S proteasome,0.0,False,CHEMBL2364701,"[{'accession': 'Q99460', 'component_descriptio...",PROTEIN COMPLEX,9606
423,[],Homo sapiens,20S proteasome,0.0,False,CHEMBL3831201,"[{'accession': 'P49721', 'component_descriptio...",PROTEIN COMPLEX,9606
424,[],Homo sapiens,Caspase,0.0,False,CHEMBL3831289,"[{'accession': 'P49662', 'component_descriptio...",PROTEIN FAMILY,9606

In [ ]:
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Rattus norvegicus,Angiotensin II receptor,25.0,False,CHEMBL2094112,"[{'accession': 'P29089', 'component_descriptio...",PROTEIN FAMILY,10116
1,[],Sus scrofa,Angiotensin type II receptor,24.0,False,CHEMBL1163122,"[{'accession': 'Q2XUH7', 'component_descriptio...",SINGLE PROTEIN,9823
2,[],Rattus norvegicus,Angiotensin II receptor (AT-1) type-1,24.0,False,CHEMBL2094250,"[{'accession': 'P29089', 'component_descriptio...",PROTEIN FAMILY,10116
3,[],Homo sapiens,Angiotensinogen,24.0,False,CHEMBL3596085,"[{'accession': 'P01019', 'component_descriptio...",SINGLE PROTEIN,9606
4,"[{'xref_id': 'P35351', 'xref_name': None, 'xre...",Rattus norvegicus,Angiotensin II type 2 (AT-2) receptor,23.0,False,CHEMBL257,"[{'accession': 'P35351', 'component_descriptio...",SINGLE PROTEIN,10116
...,...,...,...,...,...,...,...,...,...
420,[],Rattus norvegicus,Voltage-gated sodium channel,1.0,False,CHEMBL3988641,"[{'accession': 'O88457', 'component_descriptio...",PROTEIN FAMILY,10116
421,[],Homo sapiens,Voltage-gated calcium channel,0.0,False,CHEMBL2363032,"[{'accession': 'O95180', 'component_descriptio...",PROTEIN COMPLEX GROUP,9606
422,[],Homo sapiens,26S proteasome,0.0,False,CHEMBL2364701,"[{'accession': 'Q99460', 'component_descriptio...",PROTEIN COMPLEX,9606
423,[],Homo sapiens,20S proteasome,0.0,False,CHEMBL3831201,"[{'accession': 'P49721', 'component_descriptio...",PROTEIN COMPLEX,9606
424,[],Homo sapiens,Caspase,0.0,False,CHEMBL3831289,"[{'accession': 'P49662', 'component_descriptio...",PROTEIN FAMILY,9606

selecting the **bioactivity data** of the ***AGT*** in ***hypertension*** ***(1 ENTRY)***

In [ ]:
selected_target = targets.target_chembl_id[15]
selected_target

'CHEMBL227'

In [ ]:
# Searching for the specific chembl id in the above results
chembl_id = targets.loc[targets['target_chembl_id'] == 'CHEMBL227']

# Print the specific chembl id
print(chembl_id)

                                     cross_references      organism  \
15  [{'xref_id': 'P30556', 'xref_name': None, 'xre...  Homo sapiens

                         pref_name  score  species_group_flag  \
15  Type-1 angiotensin II receptor   21.0               False

   target_chembl_id                                  target_components  \
15        CHEMBL227  [{'accession': 'P30556', 'component_descriptio...

       target_type  tax_id
15  SINGLE PROTEIN    9606

Here, we will retrieve only bioactivity data for AGT  RECEPTOR (CHEMBL3596085) that are reported as IC 50  values in nM (nanomolar) unit.

filtering of the IC 50 values ⏳

In [ ]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [ ]:
df = pd.DataFrame.from_dict(res)

In [ ]:
df

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,33336,[],CHEMBL648564,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,7.3
1,None,33337,[],CHEMBL648562,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,2.0
2,None,40526,[],CHEMBL648565,Tested for binding affinity to Angiotensin II ...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,440.0
3,None,50584,[],CHEMBL648563,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,31.0
4,None,50585,[],CHEMBL647576,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,None,23289916,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,390.0
1184,None,23289917,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,32.0
1185,None,23289918,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,1010.0
1186,None,23289919,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,uM,UO_0000065,None,10.0
1187,None,23353555,[],CHEMBL4883014,Angiotensin AT1 Eurofins-Panlabs radioligand b...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,µM,None,None,7.04

In [ ]:
df.head(3)

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,33336,[],CHEMBL648564,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,7.3
1,None,33337,[],CHEMBL648562,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,2.0
2,None,40526,[],CHEMBL648565,Tested for binding affinity to Angiotensin II ...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,440.0

In [ ]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file bioactivity_data.csv.

In [ ]:
df.to_csv('bioactivity_data.csv', index=False)

## **COPYING FILE TO GOOGLE FILE**

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

Next, we create a data folder in our Colab Notebooks folder on Google Drive.

In [ ]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data3"

mkdir: cannot create directory ‘/content/gdrive/My Drive/Colab Notebooks/data3’: File exists

In [ ]:
! cp bioactivity_data.csv "/content/gdrive/My Drive/Colab Notebooks/data3"

df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

In [ ]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data3"

total 743
-rw------- 1 root root 652023 Jan 30 05:14 bioactivity_data.csv
-rw------- 1 root root 107933 Jan 29 10:12 bioactivity_preprocessed_data.csv

In [ ]:
! ls

bioactivity_data.csv  gdrive  sample_data

In [ ]:
! head bioactivity_data.csv

activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,33336,[],CHEMBL648564,"Tested for Angiotensin II receptor, type 1 affinity in the presence of 0.25% bovine serum albumin (BSA)",B,,,BAO_0000190,BAO_0000357,single protein format,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)O)cc1,,,CHEMBL1152092,Bioorg. Med. Chem. Lett.,1994.0,"{'bei': '19.17', 'le': '0.37', 'lle': '3.40', 'sei': '8.80'}",CHEMBL813,EPROSARTAN,CHEMBL813,8.14,0,http://www.openphacts.org/units/Nanomolar,174833,=,1,1,=,,IC50,nM,,7.3,CHEMBL227,Homo sapiens,Type-1 angiotensin II receptor,9606,,,IC50,nM,UO_0000065,,7.3
,33337,[],CHEMBL648562,"Tested for Angiotensin II receptor, type 1 affinity in the absence of bovine serum albumin (BSA)",B,,,BAO_0000190,BAO_0000357,single protein format,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)O)cc1,,,CHEMBL1152092,Bioorg. Med. Chem. Lett.,1994.0,"{'bei': '20.49', 'le': '0.40', 'lle': '3.96', 'sei': '9.41'}",CHEMBL813,EPROSARTAN,CHEMBL813,8.70,0,http://www.openphacts.org/units/Nanomolar,174833,=,1,1,=,,IC50,nM,,2.0,CHEMBL227,Homo sapiens,Type-1 angiotensin II receptor,9606,,,IC50,nM,UO_0000065,,2.0
,40526,[],CHEMBL648565,"Tested for binding affinity to Angiotensin II receptor, type 1",B,,,BAO_0000190,BAO_0000357,single protein format,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccccc1,,,CHEMBL1152092,Bioorg. Med. Chem. Lett.,1994.0,"{'bei': '16.71', 'le': '0.32', 'lle': '1.31', 'sei': '11.53'}",CHEMBL55508,,CHEMBL55508,6.36,0,http://www.openphacts.org/units/Nanomolar,174838,=,1,1,=,,IC50,nM,,440.0,CHEMBL227,Homo sapiens,Type-1 angiotensin II receptor,9606,,,IC50,nM,UO_0000065,,440.0
,50584,[],CHEMBL648563,"Tested for Angiotensin II receptor, type 1 affinity in the presence of 0.25% BSA",B,,,BAO_0000190,BAO_0000357,single protein format,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)O)c2ccccc12,,,CHEMBL1152092,Bioorg. Med. Chem. Lett.,1994.0,"{'bei': '15.82', 'le': '0.30', 'lle': '1.61', 'sei': '8.12'}",CHEMBL97533,,CHEMBL97533,7.51,0,http://www.openphacts.org/units/Nanomolar,174836,=,1,1,=,,IC50,nM,,31.0,CHEMBL227,Homo sapiens,Type-1 angiotensin II receptor,9606,,,IC50,nM,UO_0000065,,31.0
,50585,[],CHEMBL647576,"Tested for Angiotensin II receptor, type 1 affinity in the absence of BSA",B,,,BAO_0000190,BAO_0000357,single protein format,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)O)c2ccccc12,,,CHEMBL1152092,Bioorg. Med. Chem. Lett.,1994.0,"{'bei': '18.80', 'le': '0.36', 'lle': '3.02', 'sei': '9.65'}",CHEMBL97533,,CHEMBL97533,8.92,0,http://www.openphacts.org/units/Nanomolar,174836,=,1,1,=,,IC50,nM,,1.2,CHEMBL227,Homo sapiens,Type-1 angiotensin II receptor,9606,,,IC50,nM,UO_0000065,,1.2
,50587,[],CHEMBL648565,"Tested for binding affinity to Angiotensin II receptor, type 1",B,,,BAO_0000190,BAO_0000357,single protein format,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccccc1Cl,,,CHEMBL1152092,Bioorg. Med. Chem. Lett.,1994.0,"{'bei': '12.88', 'le': '0.26', 'lle': '-0.36', 'sei': '9.70'}",CHEMBL289543,,CHEMBL289543,5.34,0,http://www.openphacts.org/units/Nanomolar,174837,=,1,1,=,,IC50,nM,,4530.0,CHEMBL227,Homo sapiens,Type-1 angiotensin II receptor,9606,,,IC50,nM,UO_0000065,,4530.0
,73255,[],CHEMBL875934,"In vivo inhibitory concentration against Angiotensin II receptor, type 1 of human adrenal membrane",B,,,BAO_0000190,BAO_0000218,organism-based format,CCCCc1nc2ccc(NC(=O)N(C)C(C)C)cc2c(=O)n1Cc1ccc(-c2ccccc2S(=O)(=O)NC(=O)OCCC(C)C)cc1F,,,CHEMBL1150477,Bioorg. Med. Chem. Lett.,1994.0,"{'bei': '12.57', 'le': '0.24', 'lle': '1.79', 'sei': '6.24'}",CHEMBL74556,,CHEMBL74556,8.72,0,http://www.openphacts.org/units/Nanomolar,136375,=,1,1,=,,IC50,nM,,1.9,CHEMBL227,Homo sapiens,Type-1 angiotensin II receptor,9606,,,IC50,nM,UO_0000065,,1.9
,77670,[],CHEMBL875934,"In vivo inhibitory concentration against Angiotensin II receptor, type 1 of human adrenal membrane",B,,,BAO_0000190,BAO_0000218,organism-based format,CCNC(=O)Nc1ccc2nc(CC)n(Cc3ccc(-c4ccccc4S(=O)(=O)NC(=O)c4ccccc4F)cc3F)c(=O)c2c1,,,CHEMBL1150477,Bioorg. Med. Chem. Lett.,1994.0,"{'bei': '11.20', 'le': '0.21', 'lle': '2.02', 'sei': '5.19'}",CHEMBL311484,,CHEMBL311484,7.23,0,http://www.openphacts.org/units/Nanomolar,136368,=,1,1,=,,IC50,nM,,59.0,CHEMBL227,Homo sapiens,Type-1 angiotensin II receptor,9606,,,IC50,nM,UO_0000065,,59.0
,78802,[],CHEMBL875934,"In vivo inhibitory concentration against Angiotensin II receptor, type 1 of human adrenal membrane",B,,,BAO_0000190,BAO_0000218,organism-based format,CCc1nc2ccc(NC(=O)N(C)C(C)C)cc2c(=O)n1Cc1ccc(-c2ccccc2S(=O)(=O)NC(=O)OCCC2CC2)cc1F,,,CHEMBL1150477,Bioorg. Med. Chem. Lett.,1994.0,"{'bei': '12.19', 'le': '0.24', 'lle': '2.19', 'sei': '5.79'}",CHEMBL73876,,CHEMBL73876,8.09,0,http://www.openphacts.org/units/Nanomolar,136374,=,1,1,=,,IC50,nM,,8.1,CHEMBL227,Homo sapiens,Type-1 angiotensin II receptor,9606,,,IC50,nM,UO_0000065,,8.1

# Handling missing **data**

If any compounds has missing value for the standard_value column then drop it

In [ ]:
df2 = df[df.standard_value.notna()]
df2

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,33336,[],CHEMBL648564,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,7.3
1,None,33337,[],CHEMBL648562,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,2.0
2,None,40526,[],CHEMBL648565,Tested for binding affinity to Angiotensin II ...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,440.0
3,None,50584,[],CHEMBL648563,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,31.0
4,None,50585,[],CHEMBL647576,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,None,23289916,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,390.0
1184,None,23289917,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,32.0
1185,None,23289918,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,1010.0
1186,None,23289919,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,uM,UO_0000065,None,10.0
1187,None,23353555,[],CHEMBL4883014,Angiotensin AT1 Eurofins-Panlabs radioligand b...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,µM,None,None,7.04

In [ ]:
df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

<ipython-input-20-955aac5800f0>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df.canonical_smiles.notna()]

,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,33336,[],CHEMBL648564,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,7.3
1,None,33337,[],CHEMBL648562,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,2.0
2,None,40526,[],CHEMBL648565,Tested for binding affinity to Angiotensin II ...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,440.0
3,None,50584,[],CHEMBL648563,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,31.0
4,None,50585,[],CHEMBL647576,"Tested for Angiotensin II receptor, type 1 aff...",B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,None,23289916,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,390.0
1184,None,23289917,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,32.0
1185,None,23289918,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,nM,UO_0000065,None,1010.0
1186,None,23289919,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL4839255,Antagonist activity at human AT1 overexpressed...,F,None,None,BAO_0000190,BAO_0000219,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,uM,UO_0000065,None,10.0
1187,None,23353555,[],CHEMBL4883014,Angiotensin AT1 Eurofins-Panlabs radioligand b...,B,None,None,BAO_0000190,BAO_0000357,...,Homo sapiens,Type-1 angiotensin II receptor,9606,None,None,IC50,µM,None,None,7.04

Data pre-processing of the bioactivity data

Labeling compounds as either being active, inactive or intermediate

The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be active while those greater than 10,000 nM will be considered to be inactive. As for those values in between 1,000 and 10,000 nM will be referred to as intermediate.

In [ ]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

In [ ]:
df2.molecule_chembl_id

0           CHEMBL813
1           CHEMBL813
2         CHEMBL55508
3         CHEMBL97533
4         CHEMBL97533
            ...
1183    CHEMBL4859498
1184    CHEMBL4877651
1185    CHEMBL4868159
1186    CHEMBL4854916
1187    CHEMBL1800685
Name: molecule_chembl_id, Length: 1179, dtype: object

Iterate the molecule_chembl_id to a list

Iterate the molecule_chembl_id to a list

In [ ]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

### **Iterate canonical_smiles to a list**

In [ ]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

**Iterate standard_value to a list**

In [ ]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

## **Combine the 4 lists into a dataframe**

In [ ]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [ ]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL813,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,7.3
1,CHEMBL813,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,2.0
2,CHEMBL55508,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccccc1,active,440.0
3,CHEMBL97533,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,31.0
4,CHEMBL97533,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,1.2
...,...,...,...,...
1174,CHEMBL4859498,CCCCC1NC(C)(C)C(=O)N1Cc1ccc(-c2ccccc2-c2nnn[nH...,active,390.0
1175,CHEMBL4877651,CCCCC1=NC(C)(C)C(=O)N1Cc1ccc(-c2ccccc2-c2nnn[n...,active,32.0
1176,CHEMBL4868159,CCCC[C@@H]1N(Cc2ccc(-c3ccccc3-c3nnn[nH]3)cc2)C...,intermediate,1010.0
1177,CHEMBL4854916,CCCC[C@H]1N(Cc2ccc(-c3ccccc3-c3nnn[nH]3)cc2)C(...,inactive,10000.0
1178,CHEMBL1800685,O=C(O)c1cc(-c2ccc(C3CCNCC3)cc2)c2ccc(-c3ccc(C(...,active,7.04

In [ ]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL813,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,7.3
1,CHEMBL813,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,2.0
2,CHEMBL55508,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccccc1,active,440.0
3,CHEMBL97533,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,31.0
4,CHEMBL97533,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,1.2
...,...,...,...,...
1174,CHEMBL4859498,CCCCC1NC(C)(C)C(=O)N1Cc1ccc(-c2ccccc2-c2nnn[nH...,active,390.0
1175,CHEMBL4877651,CCCCC1=NC(C)(C)C(=O)N1Cc1ccc(-c2ccccc2-c2nnn[n...,active,32.0
1176,CHEMBL4868159,CCCC[C@@H]1N(Cc2ccc(-c3ccccc3-c3nnn[nH]3)cc2)C...,intermediate,1010.0
1177,CHEMBL4854916,CCCC[C@H]1N(Cc2ccc(-c3ccccc3-c3nnn[nH]3)cc2)C(...,inactive,10000.0
1178,CHEMBL1800685,O=C(O)c1cc(-c2ccc(C3CCNCC3)cc2)c2ccc(-c3ccc(C(...,active,7.04

## **Alternative method**

In [ ]:
selection = ['molecule_chembl_id', 'canonical_smiles','bioactivity_class', 'standard_value',]
df3 = df2[selection]
df3

KeyError: ignored

## concatination

In [ ]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value,0
0,CHEMBL813,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,7.3,active
1,CHEMBL813,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,2.0,active
2,CHEMBL55508,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccccc1,active,440.0,active
3,CHEMBL97533,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,31.0,active
4,CHEMBL97533,CCCCc1ncc(/C=C(\Cc2cccs2)C(=O)O)n1Cc1ccc(C(=O)...,active,1.2,active
...,...,...,...,...,...
1174,CHEMBL4859498,CCCCC1NC(C)(C)C(=O)N1Cc1ccc(-c2ccccc2-c2nnn[nH...,active,390.0,active
1175,CHEMBL4877651,CCCCC1=NC(C)(C)C(=O)N1Cc1ccc(-c2ccccc2-c2nnn[n...,active,32.0,active
1176,CHEMBL4868159,CCCC[C@@H]1N(Cc2ccc(-c3ccccc3-c3nnn[nH]3)cc2)C...,intermediate,1010.0,intermediate
1177,CHEMBL4854916,CCCC[C@H]1N(Cc2ccc(-c3ccccc3-c3nnn[nH]3)cc2)C(...,inactive,10000.0,inactive
1178,CHEMBL1800685,O=C(O)c1cc(-c2ccc(C3CCNCC3)cc2)c2ccc(-c3ccc(C(...,active,7.04,active

### ***Saves dataframe to CSV file***

In [ ]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [ ]:
! ls -l

total 756
-rw-r--r-- 1 root root 652023 Jan 30 05:13 bioactivity_data.csv
-rw-r--r-- 1 root root 107933 Jan 30 05:15 bioactivity_preprocessed_data.csv
drwx------ 5 root root   4096 Jan 30 05:14 gdrive
drwxr-xr-x 1 root root   4096 Jan 26 14:33 sample_data

*Let's copy to the Google Drive*

In [ ]:
! cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data3"

In [ ]:
! ls

bioactivity_data.csv  bioactivity_preprocessed_data.csv  gdrive  sample_data