# **Bioinformatics  Project - Computational Drug Discovery [Part 3] Descriptor Calculation and Dataset Preparation**

### **Download PaDEL-Descriptor**

In [ ]:
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
! wget https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh

--2023-01-23 14:33:18--  https://github.com/dataprofessor/bioinformatics/raw/master/padel.zip
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.zip [following]
--2023-01-23 14:33:19--  https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25768637 (25M) [application/zip]
Saving to: ‘padel.zip’

padel.zip           100%[===================>]  24.57M  --.-KB/s    in 0.1s

2023-01-23 14:33:20 (169 MB/s) - ‘padel.zip’ saved [25768637/25768637]

--2023-01-23 14:33:20--  https://github.com/dataprofessor/bioinformatics/raw/master/padel.sh
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.sh [following]
--2023-01-23 14:33:20--  https://raw.githubusercontent.com/dataprofessor/bioinformatics/master/padel.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 231 [text/plain]
Saving to: ‘padel.sh’

padel.sh            100%[===================>]     231  --.-KB/s    in 0s

2023-01-23 14:33:21 (11.1 MB/s) - ‘padel.sh’ saved [231/231]

In [ ]:
! unzip padel.zip

Archive:  padel.zip
   creating: PaDEL-Descriptor/
  inflating: __MACOSX/._PaDEL-Descriptor
  inflating: PaDEL-Descriptor/MACCSFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._MACCSFingerprinter.xml
  inflating: PaDEL-Descriptor/AtomPairs2DFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._AtomPairs2DFingerprinter.xml
  inflating: PaDEL-Descriptor/EStateFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._EStateFingerprinter.xml
  inflating: PaDEL-Descriptor/Fingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._Fingerprinter.xml
  inflating: PaDEL-Descriptor/.DS_Store
  inflating: __MACOSX/PaDEL-Descriptor/._.DS_Store
   creating: PaDEL-Descriptor/license/
  inflating: __MACOSX/PaDEL-Descriptor/._license
  inflating: PaDEL-Descriptor/KlekotaRothFingerprintCount.xml
  inflating: __MACOSX/PaDEL-Descriptor/._KlekotaRothFingerprintCount.xml
  inflating: PaDEL-Descriptor/config
  inflating: __MACOSX/PaDEL-Descriptor/._config
  inflating: PaDEL-Descriptor/PubchemFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._PubchemFingerprinter.xml
  inflating: PaDEL-Descriptor/ExtendedFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._ExtendedFingerprinter.xml
  inflating: PaDEL-Descriptor/KlekotaRothFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._KlekotaRothFingerprinter.xml
  inflating: PaDEL-Descriptor/GraphOnlyFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._GraphOnlyFingerprinter.xml
  inflating: PaDEL-Descriptor/SubstructureFingerprinter.xml
  inflating: __MACOSX/PaDEL-Descriptor/._SubstructureFingerprinter.xml
  inflating: PaDEL-Descriptor/Descriptors.xls
  inflating: __MACOSX/PaDEL-Descriptor/._Descriptors.xls
   creating: PaDEL-Descriptor/lib/
  inflating: __MACOSX/PaDEL-Descriptor/._lib
  inflating: PaDEL-Descriptor/PaDEL-Descriptor.jar
  inflating: __MACOSX/PaDEL-Descriptor/._PaDEL-Descriptor.jar
  inflating: PaDEL-Descriptor/SubstructureFingerprintCount.xml
  inflating: __MACOSX/PaDEL-Descriptor/._SubstructureFingerprintCount.xml
  inflating: PaDEL-Descriptor/AtomPairs2DFingerprintCount.xml
  inflating: __MACOSX/PaDEL-Descriptor/._AtomPairs2DFingerprintCount.xml
  inflating: PaDEL-Descriptor/descriptors.xml
  inflating: __MACOSX/PaDEL-Descriptor/._descriptors.xml
  inflating: PaDEL-Descriptor/license/lgpl-2.1.txt
  inflating: __MACOSX/PaDEL-Descriptor/license/._lgpl-2.1.txt
  inflating: PaDEL-Descriptor/license/LICENSE.txt
  inflating: __MACOSX/PaDEL-Descriptor/license/._LICENSE.txt
  inflating: PaDEL-Descriptor/license/README - CDK
  inflating: __MACOSX/PaDEL-Descriptor/license/._README - CDK
  inflating: PaDEL-Descriptor/license/lgpl.license
  inflating: __MACOSX/PaDEL-Descriptor/license/._lgpl.license
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(3).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(6).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL.jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(4).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(2).jar
  inflating: PaDEL-Descriptor/lib/xom-1.1(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._xom-1.1(1).jar
  inflating: PaDEL-Descriptor/lib/swing-worker-1.1.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._swing-worker-1.1.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(3).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(5).jar
  inflating: PaDEL-Descriptor/lib/jama(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(1).jar
  inflating: PaDEL-Descriptor/lib/appframework-1.0.3.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._appframework-1.0.3.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(7).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(7).jar
  inflating: PaDEL-Descriptor/lib/vecmath1.2-1.14.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._vecmath1.2-1.14.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(6).jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(2).jar
  inflating: PaDEL-Descriptor/lib/jama(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(6).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(2).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor(3).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(4).jar
  inflating: PaDEL-Descriptor/lib/ambit2-base-2.4.7-SNAPSHOT.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-base-2.4.7-SNAPSHOT.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(1).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(8).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(8).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(1).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs.jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(4).jar
  inflating: PaDEL-Descriptor/lib/xom-1.1.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._xom-1.1.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(5).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor(2).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(3).jar
  inflating: PaDEL-Descriptor/lib/jama(7).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(7).jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT.jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(6).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor(1).jar
  inflating: PaDEL-Descriptor/lib/jama(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(4).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(2).jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(3).jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(2).jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(3).jar
  inflating: PaDEL-Descriptor/lib/l2fprod-common-all(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._l2fprod-common-all(1).jar
  inflating: PaDEL-Descriptor/lib/jama.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama.jar
  inflating: PaDEL-Descriptor/lib/l2fprod-common-all.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._l2fprod-common-all.jar
  inflating: PaDEL-Descriptor/lib/jama(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(5).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(1).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(7).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(7).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Descriptor.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Descriptor.jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(4).jar
  inflating: PaDEL-Descriptor/lib/cdk-1.4.15.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._cdk-1.4.15.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(5).jar
  inflating: PaDEL-Descriptor/lib/ambit2-core-2.4.7-SNAPSHOT(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-core-2.4.7-SNAPSHOT(1).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(8).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(8).jar
  inflating: PaDEL-Descriptor/lib/jgrapht-0.6.0(6).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jgrapht-0.6.0(6).jar
  inflating: PaDEL-Descriptor/lib/jama(2).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(2).jar
  inflating: PaDEL-Descriptor/lib/jama(3).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._jama(3).jar
  inflating: PaDEL-Descriptor/lib/commons-cli-1.2(1).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._commons-cli-1.2(1).jar
  inflating: PaDEL-Descriptor/lib/guava-17.0.jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._guava-17.0.jar
  inflating: PaDEL-Descriptor/lib/ambit2-smarts-2.4.7-SNAPSHOT(4).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._ambit2-smarts-2.4.7-SNAPSHOT(4).jar
  inflating: PaDEL-Descriptor/lib/libPaDEL-Jobs(5).jar
  inflating: __MACOSX/PaDEL-Descriptor/lib/._libPaDEL-Jobs(5).jar

## **Load bioactivity data**

# Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the bioactivity_data_3class_pIC50.csv file that essentially contain the pIC50 values that we will be using for building a regression model.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('bioactivity_preprocessed_data.csv')

In [ ]:
df3=df

In [ ]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL443325,CNCC(=O)N[C@@H](CCCN=C(N)N)C(=O)N1C[C@@H]2C[C@...,active,23.00
1,CHEMBL417584,NCC(=O)N[C@@H](CCCN=C(N)N)C(=O)N[C@@H]1CSSC[C@...,active,27.00
2,CHEMBL414533,CNCC(=O)N[C@@H](CCCN=C(N)N)C(=O)N[C@H]1CSS[C@@...,active,0.82
3,CHEMBL3144487,CC[C@H](C)[C@H](NC(=O)[C@@H](NC[C@@H](NC(=O)[C...,active,116.00
4,CHEMBL56448,CC(C)[C@H](NC(=O)[C@H](CCCN=C(N)N)NC(=O)[C@@H]...,active,1.74
...,...,...,...,...
348,CHEMBL4872735,CCCC[C@@H](C(=O)N[C@@H](Cc1ccccc1)C(=O)O)N1Cc2...,active,24.44
349,CHEMBL4875696,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O...,active,89.22
350,CHEMBL4873899,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O...,active,118.80
351,CHEMBL4873167,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O...,active,59.28
352,CHEMBL4854474,CC[C@H](C)[C@H](NC(=O)[C@H](Cc1ccc(O)cc1)NC(=O...,active,315.40

In [ ]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [ ]:
df4=df3.head(1030)

In [ ]:
df4

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.136677
1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.698970
2,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.356547
3,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.508638
4,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.920819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.982967
1026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.777284
1027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.958607
1028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.301030
1029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.638272

In [ ]:
! cat molecule.smi | head -5

CNCC(=O)N[C@@H](CCCN=C(N)N)C(=O)N1C[C@@H]2C[C@H]1C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)N[C@H](C(=O)N[C@@H](Cc1c[nH]cn1)C(=O)N1CCC[C@H]1C(=O)N[C@@H](Cc1ccccc1)C(=O)O)CSSC[C@H](C(=O)N[C@H](Cc1c[nH]cn1)C(=O)N1CCC[C@@H]1C(=O)N[C@H](Cc1ccccc1)C(=O)O)NC(=O)[C@@H](Cc1ccc(O)cc1)NC(=O)[C@H]1C[C@H](CN1C(=O)[C@@H](CCCN=C(N)N)NC(=O)CNC)SS2	CHEMBL443325
NCC(=O)N[C@@H](CCCN=C(N)N)C(=O)N[C@@H]1CSSC[C@H](C(=O)N[C@@H](Cc2c[nH]cn2)C(=O)N2CCC[C@@H]2C(=O)N[C@@H](Cc2ccccc2)C(=O)O)NC(=O)[C@@H](Cc2ccc(O)cc2)NC1=O	CHEMBL417584
CNCC(=O)N[C@@H](CCCN=C(N)N)C(=O)N[C@H]1CSS[C@@H]2C[C@@H](C(=O)N[C@@H](Cc3c[nH]cn3)C(=O)N3CCC[C@H]3C(=O)N[C@@H](Cc3ccccc3)C(=O)O)N(C2)C(=O)[C@H](Cc2ccc(O)cc2)NC1=O	CHEMBL414533
CC[C@H](C)[C@H](NC(=O)[C@@H](NC[C@@H](NC(=O)[C@H](CCCNC(=N)N)NC(=O)[C@@H](N)CC(=O)O)C(C)C)c1ccc(O)cc1)C(=O)N[C@@H](Cc1c[nH]cn1)C(=O)N1CCC[C@H]1C(=O)N[C@@H](Cc1ccccc1)C(=O)N[C@@H](Cc1c[nH]cn1)C(=O)C(N)[C@H](CC(C)C)C(C)=O	CHEMBL3144487
CC(C)[C@H](NC(=O)[C@H](CCCN=C(N)N)NC(=O)[C@@H](N)CC(=O)O)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)N[C@H](C(=O)N[C@@H](Cc1c[nH]cn1)C(=O)N1CCC[C@H]1C(=O)O)C(C)C	CHEMBL56448

In [ ]:
! cat molecule.smi | wc -l

353

# **Calculate fingerprint descriptors**

### **Calculate PaDEL descriptors**

In [ ]:
! cat padel.sh

java -Xms1G -Xmx1G -Djava.awt.headless=true -jar ./PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./PaDEL-Descriptor/PubchemFingerprinter.xml -dir ./ -file descriptors_output.csv

In [ ]:
! bash padel.sh

Processing CHEMBL443325 in molecule.smi (1/353).
Processing CHEMBL417584 in molecule.smi (2/353).
Processing CHEMBL414533 in molecule.smi (3/353). Average speed: 8.51 s/mol.
Processing CHEMBL3144487 in molecule.smi (4/353). Average speed: 10.78 s/mol.
Processing CHEMBL56448 in molecule.smi (5/353). Average speed: 4.00 s/mol.
Processing CHEMBL411657 in molecule.smi (6/353). Average speed: 3.35 s/mol.
Processing CHEMBL408403 in molecule.smi (7/353). Average speed: 2.78 s/mol.
Processing CHEMBL408885 in molecule.smi (8/353). Average speed: 2.57 s/mol.
Processing CHEMBL385283 in molecule.smi (9/353). Average speed: 2.41 s/mol.
Processing CHEMBL384352 in molecule.smi (10/353). Average speed: 2.25 s/mol.
Processing CHEMBL408773 in molecule.smi (11/353). Average speed: 2.06 s/mol.
Processing CHEMBL413925 in molecule.smi (12/353). Average speed: 1.96 s/mol.
Processing CHEMBL264450 in molecule.smi (14/353). Average speed: 1.75 s/mol.
Processing CHEMBL408886 in molecule.smi (13/353). Average speed: 1.82 s/mol.
Processing CHEMBL384125 in molecule.smi (15/353). Average speed: 1.65 s/mol.
Processing CHEMBL406290 in molecule.smi (16/353). Average speed: 1.73 s/mol.
Processing CHEMBL440063 in molecule.smi (17/353). Average speed: 1.53 s/mol.
Processing CHEMBL413034 in molecule.smi (18/353). Average speed: 1.50 s/mol.
Processing CHEMBL938 in molecule.smi (19/353). Average speed: 1.49 s/mol.
Processing CHEMBL74556 in molecule.smi (20/353). Average speed: 1.55 s/mol.
Processing CHEMBL311484 in molecule.smi (22/353). Average speed: 1.37 s/mol.
Processing CHEMBL265790 in molecule.smi (21/353). Average speed: 1.39 s/mol.
Processing CHEMBL73876 in molecule.smi (23/353). Average speed: 1.34 s/mol.
Processing CHEMBL302102 in molecule.smi (24/353). Average speed: 1.29 s/mol.
Processing CHEMBL424004 in molecule.smi (26/353). Average speed: 1.24 s/mol.
Processing CHEMBL305647 in molecule.smi (25/353). Average speed: 1.26 s/mol.
Processing CHEMBL74442 in molecule.smi (27/353). Average speed: 1.21 s/mol.
Processing CHEMBL17487 in molecule.smi (28/353). Average speed: 1.17 s/mol.
Processing CHEMBL338514 in molecule.smi (30/353). Average speed: 1.13 s/mol.
Processing CHEMBL305956 in molecule.smi (29/353). Average speed: 1.15 s/mol.
Processing CHEMBL125542 in molecule.smi (32/353). Average speed: 1.10 s/mol.
Processing CHEMBL306361 in molecule.smi (31/353). Average speed: 1.10 s/mol.
Processing CHEMBL170290 in molecule.smi (33/353). Average speed: 1.06 s/mol.
Processing CHEMBL263191 in molecule.smi (34/353). Average speed: 1.03 s/mol.
Processing CHEMBL415073 in molecule.smi (35/353). Average speed: 1.03 s/mol.
Processing CHEMBL307430 in molecule.smi (36/353). Average speed: 1.00 s/mol.
Processing CHEMBL194608 in molecule.smi (37/353). Average speed: 0.99 s/mol.
Processing CHEMBL75401 in molecule.smi (38/353). Average speed: 0.97 s/mol.
Processing CHEMBL339544 in molecule.smi (39/353). Average speed: 0.96 s/mol.
Processing CHEMBL259843 in molecule.smi (40/353). Average speed: 0.95 s/mol.
Processing CHEMBL76821 in molecule.smi (42/353). Average speed: 0.92 s/mol.
Processing CHEMBL306362 in molecule.smi (41/353). Average speed: 0.93 s/mol.
Processing CHEMBL263452 in molecule.smi (43/353). Average speed: 0.93 s/mol.
Processing CHEMBL74144 in molecule.smi (44/353). Average speed: 0.89 s/mol.
Processing CHEMBL157946 in molecule.smi (45/353). Average speed: 0.89 s/mol.
Processing CHEMBL311386 in molecule.smi (46/353). Average speed: 0.87 s/mol.
Processing CHEMBL311160 in molecule.smi (47/353). Average speed: 0.87 s/mol.
Processing CHEMBL307290 in molecule.smi (48/353). Average speed: 0.86 s/mol.
Processing CHEMBL157510 in molecule.smi (50/353). Average speed: 0.84 s/mol.
Processing CHEMBL74476 in molecule.smi (49/353). Average speed: 0.85 s/mol.
Processing CHEMBL350875 in molecule.smi (51/353). Average speed: 0.83 s/mol.
Processing CHEMBL156165 in molecule.smi (52/353). Average speed: 0.82 s/mol.
Processing CHEMBL158557 in molecule.smi (53/353). Average speed: 0.82 s/mol.
Processing CHEMBL348363 in molecule.smi (54/353). Average speed: 0.81 s/mol.
Processing CHEMBL155728 in molecule.smi (55/353). Average speed: 0.81 s/mol.
Processing CHEMBL156129 in molecule.smi (56/353). Average speed: 0.80 s/mol.
Processing CHEMBL155847 in molecule.smi (57/353). Average speed: 0.79 s/mol.
Processing CHEMBL160930 in molecule.smi (58/353). Average speed: 0.79 s/mol.
Processing CHEMBL290829 in molecule.smi (59/353). Average speed: 0.78 s/mol.
Processing CHEMBL423236 in molecule.smi (60/353). Average speed: 0.78 s/mol.
Processing CHEMBL157946 in molecule.smi (61/353). Average speed: 0.77 s/mol.
Processing CHEMBL154057 in molecule.smi (63/353). Average speed: 0.76 s/mol.
Processing CHEMBL155987 in molecule.smi (62/353). Average speed: 0.77 s/mol.
Processing CHEMBL156587 in molecule.smi (64/353). Average speed: 0.76 s/mol.
Processing CHEMBL350220 in molecule.smi (66/353). Average speed: 0.77 s/mol.
Processing CHEMBL155836 in molecule.smi (65/353). Average speed: 0.75 s/mol.
Processing CHEMBL155836 in molecule.smi (67/353). Average speed: 0.75 s/mol.
Processing CHEMBL156100 in molecule.smi (68/353). Average speed: 0.75 s/mol.
Processing CHEMBL155938 in molecule.smi (69/353). Average speed: 0.74 s/mol.
Processing CHEMBL128416 in molecule.smi (70/353). Average speed: 0.74 s/mol.
Processing CHEMBL430997 in molecule.smi (71/353). Average speed: 0.73 s/mol.
Processing CHEMBL308943 in molecule.smi (73/353). Average speed: 0.73 s/mol.
Processing CHEMBL71953 in molecule.smi (72/353). Average speed: 0.73 s/mol.
Processing CHEMBL309820 in molecule.smi (74/353). Average speed: 0.73 s/mol.
Processing CHEMBL273992 in molecule.smi (75/353). Average speed: 0.73 s/mol.
Processing CHEMBL74113 in molecule.smi (76/353). Average speed: 0.72 s/mol.
Processing CHEMBL73780 in molecule.smi (78/353). Average speed: 0.71 s/mol.
Processing CHEMBL309365 in molecule.smi (77/353). Average speed: 0.72 s/mol.
Processing CHEMBL302959 in molecule.smi (79/353). Average speed: 0.71 s/mol.
Processing CHEMBL309367 in molecule.smi (80/353). Average speed: 0.71 s/mol.
Processing CHEMBL308361 in molecule.smi (81/353). Average speed: 0.70 s/mol.
Processing CHEMBL303426 in molecule.smi (82/353). Average speed: 0.70 s/mol.
Processing CHEMBL306961 in molecule.smi (83/353). Average speed: 0.69 s/mol.
Processing CHEMBL72721 in molecule.smi (84/353). Average speed: 0.69 s/mol.
Processing CHEMBL308703 in molecule.smi (86/353). Average speed: 0.69 s/mol.
Processing CHEMBL70389 in molecule.smi (85/353). Average speed: 0.69 s/mol.
Processing CHEMBL995 in molecule.smi (88/353). Average speed: 0.68 s/mol.
Processing CHEMBL72819 in molecule.smi (87/353). Average speed: 0.68 s/mol.
Processing CHEMBL306216 in molecule.smi (89/353). Average speed: 0.67 s/mol.
Processing CHEMBL409170 in molecule.smi (90/353). Average speed: 0.68 s/mol.
Processing CHEMBL307321 in molecule.smi (91/353). Average speed: 0.67 s/mol.
Processing CHEMBL70638 in molecule.smi (92/353). Average speed: 0.66 s/mol.
Processing CHEMBL304620 in molecule.smi (93/353). Average speed: 0.66 s/mol.
Processing CHEMBL306922 in molecule.smi (94/353). Average speed: 0.66 s/mol.
Processing CHEMBL70796 in molecule.smi (96/353). Average speed: 0.66 s/mol.
Processing CHEMBL302760 in molecule.smi (95/353). Average speed: 0.65 s/mol.
Processing CHEMBL307756 in molecule.smi (97/353). Average speed: 0.65 s/mol.
Processing CHEMBL309165 in molecule.smi (98/353). Average speed: 0.65 s/mol.
Processing CHEMBL72409 in molecule.smi (99/353). Average speed: 0.65 s/mol.
Processing CHEMBL70801 in molecule.smi (100/353). Average speed: 0.65 s/mol.
Processing CHEMBL306489 in molecule.smi (101/353). Average speed: 0.64 s/mol.
Processing CHEMBL304137 in molecule.smi (102/353). Average speed: 0.64 s/mol.
Processing CHEMBL70770 in molecule.smi (103/353). Average speed: 0.64 s/mol.
Processing CHEMBL71069 in molecule.smi (104/353). Average speed: 0.64 s/mol.
Processing CHEMBL306638 in molecule.smi (105/353). Average speed: 0.63 s/mol.
Processing CHEMBL71286 in molecule.smi (106/353). Average speed: 0.64 s/mol.
Processing CHEMBL306923 in molecule.smi (107/353). Average speed: 0.63 s/mol.
Processing CHEMBL307008 in molecule.smi (108/353). Average speed: 0.63 s/mol.
Processing CHEMBL307359 in molecule.smi (109/353). Average speed: 0.63 s/mol.
Processing CHEMBL306473 in molecule.smi (110/353). Average speed: 0.63 s/mol.
Processing CHEMBL307866 in molecule.smi (112/353). Average speed: 0.63 s/mol.
Processing CHEMBL309790 in molecule.smi (111/353). Average speed: 0.63 s/mol.
Processing CHEMBL306340 in molecule.smi (114/353). Average speed: 0.62 s/mol.
Processing CHEMBL307318 in molecule.smi (113/353). Average speed: 0.63 s/mol.
Processing CHEMBL302485 in molecule.smi (115/353). Average speed: 0.62 s/mol.
Processing CHEMBL304065 in molecule.smi (116/353). Average speed: 0.62 s/mol.
Processing CHEMBL70935 in molecule.smi (118/353). Average speed: 0.62 s/mol.
Processing CHEMBL74573 in molecule.smi (117/353). Average speed: 0.62 s/mol.
Processing CHEMBL305238 in molecule.smi (119/353). Average speed: 0.62 s/mol.
Processing CHEMBL311625 in molecule.smi (120/353). Average speed: 0.62 s/mol.
Processing CHEMBL309455 in molecule.smi (121/353). Average speed: 0.62 s/mol.
Processing CHEMBL305239 in molecule.smi (122/353). Average speed: 0.61 s/mol.
Processing CHEMBL311018 in molecule.smi (123/353). Average speed: 0.61 s/mol.
Processing CHEMBL115021 in molecule.smi (124/353). Average speed: 0.61 s/mol.
Processing CHEMBL305369 in molecule.smi (125/353). Average speed: 0.61 s/mol.
Processing CHEMBL72249 in molecule.smi (126/353). Average speed: 0.61 s/mol.
Processing CHEMBL305017 in molecule.smi (127/353). Average speed: 0.62 s/mol.
Processing CHEMBL306186 in molecule.smi (128/353). Average speed: 0.61 s/mol.
Processing CHEMBL70868 in molecule.smi (129/353). Average speed: 0.61 s/mol.
Processing CHEMBL302579 in molecule.smi (130/353). Average speed: 0.61 s/mol.
Processing CHEMBL73369 in molecule.smi (131/353). Average speed: 0.61 s/mol.
Processing CHEMBL71125 in molecule.smi (132/353). Average speed: 0.61 s/mol.
Processing CHEMBL74514 in molecule.smi (133/353). Average speed: 0.61 s/mol.
Processing CHEMBL303427 in molecule.smi (134/353). Average speed: 0.61 s/mol.
Processing CHEMBL71220 in molecule.smi (136/353). Average speed: 0.61 s/mol.
Processing CHEMBL419073 in molecule.smi (135/353). Average speed: 0.61 s/mol.
Processing CHEMBL70793 in molecule.smi (137/353). Average speed: 0.61 s/mol.
Processing CHEMBL69839 in molecule.smi (138/353). Average speed: 0.61 s/mol.
Processing CHEMBL70353 in molecule.smi (140/353). Average speed: 0.61 s/mol.
Processing CHEMBL430792 in molecule.smi (139/353). Average speed: 0.61 s/mol.
Processing CHEMBL70100 in molecule.smi (141/353). Average speed: 0.61 s/mol.
Processing CHEMBL70726 in molecule.smi (142/353). Average speed: 0.61 s/mol.
Processing CHEMBL70789 in molecule.smi (143/353). Average speed: 0.61 s/mol.
Processing CHEMBL70843 in molecule.smi (144/353). Average speed: 0.61 s/mol.
Processing CHEMBL306924 in molecule.smi (145/353). Average speed: 0.61 s/mol.
Processing CHEMBL72595 in molecule.smi (146/353). Average speed: 0.61 s/mol.
Processing CHEMBL302964 in molecule.smi (147/353). Average speed: 0.61 s/mol.
Processing CHEMBL74236 in molecule.smi (148/353). Average speed: 0.61 s/mol.
Processing CHEMBL309081 in molecule.smi (150/353). Average speed: 0.61 s/mol.
Processing CHEMBL308323 in molecule.smi (149/353). Average speed: 0.61 s/mol.
Processing CHEMBL306435 in molecule.smi (151/353). Average speed: 0.61 s/mol.
Processing CHEMBL72099 in molecule.smi (152/353). Average speed: 0.61 s/mol.
Processing CHEMBL311253 in molecule.smi (153/353). Average speed: 0.61 s/mol.
Processing CHEMBL308482 in molecule.smi (154/353). Average speed: 0.61 s/mol.
Processing CHEMBL74069 in molecule.smi (156/353). Average speed: 0.61 s/mol.
Processing CHEMBL303647 in molecule.smi (155/353). Average speed: 0.61 s/mol.
Processing CHEMBL70867 in molecule.smi (158/353). Average speed: 0.61 s/mol.
Processing CHEMBL69721 in molecule.smi (157/353). Average speed: 0.61 s/mol.
Processing CHEMBL73283 in molecule.smi (159/353). Average speed: 0.60 s/mol.
Processing CHEMBL306761 in molecule.smi (160/353). Average speed: 0.61 s/mol.
Processing CHEMBL312301 in molecule.smi (161/353). Average speed: 0.60 s/mol.
Processing CHEMBL71639 in molecule.smi (162/353). Average speed: 0.61 s/mol.
Processing CHEMBL70370 in molecule.smi (163/353). Average speed: 0.60 s/mol.
Processing CHEMBL70161 in molecule.smi (164/353). Average speed: 0.60 s/mol.
Processing CHEMBL71172 in molecule.smi (165/353). Average speed: 0.60 s/mol.
Processing CHEMBL286134 in molecule.smi (166/353). Average speed: 0.60 s/mol.
Processing CHEMBL39352 in molecule.smi (167/353). Average speed: 0.60 s/mol.
Processing CHEMBL36324 in molecule.smi (169/353). Average speed: 0.60 s/mol.
Processing CHEMBL39996 in molecule.smi (168/353). Average speed: 0.60 s/mol.
Processing CHEMBL290829 in molecule.smi (171/353). Average speed: 0.59 s/mol.
Processing CHEMBL34124 in molecule.smi (170/353). Average speed: 0.60 s/mol.
Processing CHEMBL290286 in molecule.smi (172/353). Average speed: 0.59 s/mol.
Processing CHEMBL157946 in molecule.smi (173/353). Average speed: 0.59 s/mol.
Processing CHEMBL313005 in molecule.smi (174/353). Average speed: 0.59 s/mol.
Processing CHEMBL328480 in molecule.smi (175/353). Average speed: 0.59 s/mol.
Processing CHEMBL89052 in molecule.smi (177/353). Average speed: 0.59 s/mol.
Processing CHEMBL313073 in molecule.smi (176/353). Average speed: 0.59 s/mol.
Processing CHEMBL330744 in molecule.smi (179/353). Average speed: 0.59 s/mol.
Processing CHEMBL89769 in molecule.smi (178/353). Average speed: 0.59 s/mol.
Processing CHEMBL432378 in molecule.smi (180/353). Average speed: 0.59 s/mol.
Processing CHEMBL80370 in molecule.smi (181/353). Average speed: 0.58 s/mol.
Processing CHEMBL89463 in molecule.smi (182/353). Average speed: 0.58 s/mol.
Processing CHEMBL288705 in molecule.smi (183/353). Average speed: 0.58 s/mol.
Processing CHEMBL315275 in molecule.smi (184/353). Average speed: 0.58 s/mol.
Processing CHEMBL315994 in molecule.smi (186/353). Average speed: 0.58 s/mol.
Processing CHEMBL314506 in molecule.smi (185/353). Average speed: 0.58 s/mol.
Processing CHEMBL316021 in molecule.smi (187/353). Average speed: 0.58 s/mol.
Processing CHEMBL81236 in molecule.smi (188/353). Average speed: 0.57 s/mol.
Processing CHEMBL88446 in molecule.smi (190/353). Average speed: 0.57 s/mol.
Processing CHEMBL315327 in molecule.smi (189/353). Average speed: 0.57 s/mol.
Processing CHEMBL330302 in molecule.smi (191/353). Average speed: 0.57 s/mol.
Processing CHEMBL89053 in molecule.smi (192/353). Average speed: 0.57 s/mol.
Processing CHEMBL275449 in molecule.smi (193/353). Average speed: 0.57 s/mol.
Processing CHEMBL86617 in molecule.smi (194/353). Average speed: 0.57 s/mol.
Processing CHEMBL314827 in molecule.smi (195/353). Average speed: 0.57 s/mol.
Processing CHEMBL41194 in molecule.smi (196/353). Average speed: 0.57 s/mol.
Processing CHEMBL289614 in molecule.smi (198/353). Average speed: 0.57 s/mol.
Processing CHEMBL288174 in molecule.smi (197/353). Average speed: 0.57 s/mol.
Processing CHEMBL290214 in molecule.smi (200/353). Average speed: 0.56 s/mol.
Processing CHEMBL39959 in molecule.smi (199/353). Average speed: 0.56 s/mol.
Processing CHEMBL436396 in molecule.smi (201/353). Average speed: 0.56 s/mol.
Processing CHEMBL276674 in molecule.smi (202/353). Average speed: 0.56 s/mol.
Processing CHEMBL122158 in molecule.smi (203/353). Average speed: 0.56 s/mol.
Processing CHEMBL340078 in molecule.smi (204/353). Average speed: 0.56 s/mol.
Processing CHEMBL338342 in molecule.smi (205/353). Average speed: 0.56 s/mol.
Processing CHEMBL125760 in molecule.smi (206/353). Average speed: 0.56 s/mol.
Processing CHEMBL331632 in molecule.smi (207/353). Average speed: 0.56 s/mol.
Processing CHEMBL334300 in molecule.smi (208/353). Average speed: 0.56 s/mol.
Processing CHEMBL122401 in molecule.smi (209/353). Average speed: 0.56 s/mol.
Processing CHEMBL332576 in molecule.smi (210/353). Average speed: 0.56 s/mol.
Processing CHEMBL124903 in molecule.smi (211/353). Average speed: 0.56 s/mol.
Processing CHEMBL339722 in molecule.smi (212/353). Average speed: 0.55 s/mol.
Processing CHEMBL122917 in molecule.smi (214/353). Average speed: 0.55 s/mol.
Processing CHEMBL339722 in molecule.smi (213/353). Average speed: 0.55 s/mol.
Processing CHEMBL435811 in molecule.smi (215/353). Average speed: 0.55 s/mol.
Processing CHEMBL124771 in molecule.smi (216/353). Average speed: 0.55 s/mol.
Processing CHEMBL444065 in molecule.smi (217/353). Average speed: 0.55 s/mol.
Processing CHEMBL341369 in molecule.smi (218/353). Average speed: 0.55 s/mol.
Processing CHEMBL340473 in molecule.smi (220/353). Average speed: 0.55 s/mol.
Processing CHEMBL273542 in molecule.smi (219/353). Average speed: 0.55 s/mol.
Processing CHEMBL332909 in molecule.smi (222/353). Average speed: 0.55 s/mol.
Processing CHEMBL338027 in molecule.smi (221/353). Average speed: 0.55 s/mol.
Processing CHEMBL338888 in molecule.smi (223/353). Average speed: 0.55 s/mol.
Processing CHEMBL339040 in molecule.smi (224/353). Average speed: 0.55 s/mol.
Processing CHEMBL339256 in molecule.smi (225/353). Average speed: 0.55 s/mol.
Processing CHEMBL339256 in molecule.smi (226/353). Average speed: 0.55 s/mol.
Processing CHEMBL125280 in molecule.smi (227/353). Average speed: 0.54 s/mol.
Processing CHEMBL339004 in molecule.smi (228/353). Average speed: 0.54 s/mol.
Processing CHEMBL338434 in molecule.smi (229/353). Average speed: 0.55 s/mol.
Processing CHEMBL338434 in molecule.smi (230/353). Average speed: 0.55 s/mol.
Processing CHEMBL339113 in molecule.smi (231/353). Average speed: 0.55 s/mol.
Processing CHEMBL125008 in molecule.smi (232/353). Average speed: 0.54 s/mol.
Processing CHEMBL122380 in molecule.smi (233/353). Average speed: 0.54 s/mol.
Processing CHEMBL333224 in molecule.smi (234/353). Average speed: 0.54 s/mol.
Processing CHEMBL338687 in molecule.smi (235/353). Average speed: 0.54 s/mol.
Processing CHEMBL338137 in molecule.smi (237/353). Average speed: 0.54 s/mol.
Processing CHEMBL421478 in molecule.smi (236/353). Average speed: 0.54 s/mol.
Processing CHEMBL122273 in molecule.smi (238/353). Average speed: 0.54 s/mol.
Processing CHEMBL339605 in molecule.smi (239/353). Average speed: 0.54 s/mol.
Processing CHEMBL121872 in molecule.smi (241/353). Average speed: 0.54 s/mol.
Processing CHEMBL331455 in molecule.smi (240/353). Average speed: 0.54 s/mol.
Processing CHEMBL331450 in molecule.smi (242/353). Average speed: 0.54 s/mol.
Processing CHEMBL339672 in molecule.smi (243/353). Average speed: 0.54 s/mol.
Processing CHEMBL338433 in molecule.smi (244/353). Average speed: 0.54 s/mol.
Processing CHEMBL331507 in molecule.smi (245/353). Average speed: 0.54 s/mol.
Processing CHEMBL338889 in molecule.smi (246/353). Average speed: 0.54 s/mol.
Processing CHEMBL340632 in molecule.smi (247/353). Average speed: 0.54 s/mol.
Processing CHEMBL122157 in molecule.smi (248/353). Average speed: 0.54 s/mol.
Processing CHEMBL121907 in molecule.smi (249/353). Average speed: 0.53 s/mol.
Processing CHEMBL339806 in molecule.smi (250/353). Average speed: 0.53 s/mol.
Processing CHEMBL346728 in molecule.smi (251/353). Average speed: 0.53 s/mol.
Processing CHEMBL267354 in molecule.smi (252/353). Average speed: 0.53 s/mol.
Processing CHEMBL39959 in molecule.smi (253/353). Average speed: 0.53 s/mol.
Processing CHEMBL34124 in molecule.smi (254/353). Average speed: 0.53 s/mol.
Processing CHEMBL292277 in molecule.smi (255/353). Average speed: 0.53 s/mol.
Processing CHEMBL96554 in molecule.smi (256/353). Average speed: 0.53 s/mol.
Processing CHEMBL313868 in molecule.smi (257/353). Average speed: 0.53 s/mol.
Processing CHEMBL74573 in molecule.smi (258/353). Average speed: 0.53 s/mol.
Processing CHEMBL308703 in molecule.smi (259/353). Average speed: 0.53 s/mol.

In [ ]:
! ls -l

total 25220
-rw-r--r-- 1 root root     1124 Jan  3 06:10 bioactivity_preprocessed_data.csv
-rw-r--r-- 1 root root    25566 Jan  3 06:16 descriptors_output.csv
drwxr-xr-x 3 root root     4096 Jan  3 05:19 __MACOSX
-rw-r--r-- 1 root root      936 Jan  3 06:11 molecule.smi
drwxrwxr-x 4 root root     4096 May 30  2020 PaDEL-Descriptor
-rw-r--r-- 1 root root      231 Jan  3 05:18 padel.sh
-rw-r--r-- 1 root root 25768637 Jan  3 05:18 padel.zip
drwxr-xr-x 1 root root     4096 Dec 20 20:19 sample_data

# **Preparing the X and Y Data Matrices**

## **X data matrix**

In [ ]:
df3_X = pd.read_csv('descriptors_output.csv')

In [ ]:
df3_X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL252417,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL429844,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL398940,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL429844,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL3235416,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,CHEMBL429844,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,CHEMBL4633785,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7,CHEMBL436639,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,1,1,0,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

# **Y variable**

## Convert IC50 to pIC50

In [ ]:
df3_Y = df3['pIC50']
df3_Y

KeyError: ignored